name: K8MRP Build

on:
  push:
    branches: [ main, master ]
    tags: [ "v*", "alpha*", "beta*" ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: k8mrp_rewrite     # <-- set this to your project folder
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx3g -XX:+UseG1GC'"

    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Validate wrapper ONLY if it exists, and in the right folder
      - name: Validate Gradle wrapper
        if: ${{ hashFiles(format('{0}/gradle/wrapper/gradle-wrapper.jar', env.PROJECT_DIR)) != '' }}
        uses: gradle/wrapper-validation-action@v2
        with:
          build-root-directory: ${{ env.PROJECT_DIR }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Show Gradle version
        run: ./gradlew --version

      - name: Build
        run: ./gradlew clean build --stacktrace --no-daemon

      - name: Upload mod jars
        uses: actions/upload-artifact@v4
        with:
          name: k8mrp-mod-jars
          path: build/libs/*.jar
          if-no-files-found: error

      - name: Release on tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
