name: K8MRP Build (stable Loom + Gradle)

on:
  push:
    branches: [ main, master ]
    tags: [ "v*", "alpha*", "beta*" ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      project-dir:
        description: "Path to the Gradle project ('.' if repo root)"
        required: false
        default: "."

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      # Known-good pair: Loom 1.11 + Gradle 8.10.2 (JDK 21)
      LOOM_VERSION: "1.11"
      GRADLE_VERSION: "8.10.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set PROJECT_DIR
        shell: bash
        run: |
          PD="${{ github.event.inputs.project-dir }}"
          if [ -z "$PD" ]; then PD="."; fi
          echo "PROJECT_DIR=$PD" >> "$GITHUB_ENV"
          echo "Using PROJECT_DIR=$PD"

      - name: Show layout
        shell: bash
        run: |
          echo "PROJECT_DIR=$PROJECT_DIR"
          ls -la
          echo "----"
          ls -la "$PROJECT_DIR" || true
          echo "----"
          find "$PROJECT_DIR" -maxdepth 3 -name gradlew -print || true

      - name: Ensure pluginManagement repos (Fabric maven)
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -e
          FILE=""
          if [ -f "settings.gradle.kts" ]; then FILE="settings.gradle.kts"; fi
          if [ -z "$FILE" ] && [ -f "settings.gradle" ]; then FILE="settings.gradle"; fi
          if [ -z "$FILE" ]; then
            echo "No settings.gradle(.kts); creating settings.gradle with pluginManagement."
            printf '%s\n' \
'pluginManagement {' \
'  repositories {' \
'    maven { url = uri("https://maven.fabricmc.net/") }' \
'    gradlePluginPortal()' \
'    mavenCentral()' \
'  }' \
'}' \
'rootProject.name = "K8MRP"' \
> settings.gradle
          else
            if ! grep -q "pluginManagement" "$FILE"; then
              echo "Appending pluginManagement block to $FILE"
              {
                echo
                echo 'pluginManagement {'
                echo '  repositories {'
                echo '    maven { url = uri("https://maven.fabricmc.net/") }'
                echo '    gradlePluginPortal()'
                echo '    mavenCentral()'
                echo '  }'
                echo '}'
              } >> "$FILE"
            fi
          fi

      - name: Pin Fabric Loom to a stable version
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -e
          for f in build.gradle build.gradle.kts settings.gradle settings.gra
